const mongoose = require("mongoose");
require("dotenv").config();
const connectDB = require("./config/db");

const Medicine = require("./models/Medicine");

const seedAlternatives = async () => {
  await connectDB();
  console.log("🌱 Seeding additional alternatives...\n");

  const alternatives = [
    // ═══════════════════════════════════════════════
    //  PARACETAMOL ALTERNATIVES (Crocin/Dolo equivalents)
    // ═══════════════════════════════════════════════
    {
      name: "Calpol 500",
      genericName: "Paracetamol",
      activeIngredients: [{ name: "Paracetamol", strength: "500mg" }],
      therapeuticCategory: "Antipyretic",
      dosageForm: "Tablet",
      description: "Trusted paracetamol brand for fever and pain relief in adults and children.",
      sideEffects: ["Nausea", "Rash", "Liver damage (overdose)"],
      warnings: ["Do not exceed 4g per day"],
      packSize: "15 tablets",
      manufacturer: "GlaxoSmithKline",
      brand: "Calpol",
      isBranded: true,
      averagePrice: 22,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "P-500",
      genericName: "Paracetamol",
      activeIngredients: [{ name: "Paracetamol", strength: "500mg" }],
      therapeuticCategory: "Antipyretic",
      dosageForm: "Tablet",
      description: "Affordable paracetamol for headache, toothache, and fever.",
      sideEffects: ["Nausea", "Allergic reactions"],
      packSize: "10 tablets",
      manufacturer: "GlaxoSmithKline",
      brand: "P-500",
      isBranded: true,
      averagePrice: 12,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Pacimol 650",
      genericName: "Paracetamol",
      activeIngredients: [{ name: "Paracetamol", strength: "650mg" }],
      therapeuticCategory: "Antipyretic",
      dosageForm: "Tablet",
      description: "Pain reliever and fever reducer. Popular alternative to Dolo 650.",
      sideEffects: ["Nausea", "Rash"],
      warnings: ["Do not exceed recommended dose"],
      packSize: "15 tablets",
      manufacturer: "Ipca Laboratories",
      brand: "Pacimol",
      isBranded: true,
      averagePrice: 28,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Metacin 500",
      genericName: "Paracetamol",
      activeIngredients: [{ name: "Paracetamol", strength: "500mg" }],
      therapeuticCategory: "Antipyretic",
      dosageForm: "Tablet",
      description: "Effective for mild to moderate pain and fever.",
      sideEffects: ["Nausea", "Skin rash"],
      packSize: "10 tablets",
      manufacturer: "ICPA Health Products",
      brand: "Metacin",
      isBranded: true,
      averagePrice: 15,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Pyrigesic 650",
      genericName: "Paracetamol",
      activeIngredients: [{ name: "Paracetamol", strength: "650mg" }],
      therapeuticCategory: "Antipyretic",
      dosageForm: "Tablet",
      description: "Paracetamol tablet for relief from fever and body pain.",
      sideEffects: ["Nausea", "Allergic reaction"],
      packSize: "15 tablets",
      manufacturer: "East India Pharma",
      brand: "Pyrigesic",
      isBranded: true,
      averagePrice: 18,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Fepanil 650",
      genericName: "Paracetamol",
      activeIngredients: [{ name: "Paracetamol", strength: "650mg" }],
      therapeuticCategory: "Antipyretic",
      dosageForm: "Tablet",
      description: "Cost-effective paracetamol for fever and pain management.",
      sideEffects: ["Nausea"],
      packSize: "10 tablets",
      manufacturer: "Leeford Healthcare",
      brand: "Fepanil",
      isBranded: true,
      averagePrice: 20,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Doliprane 500",
      genericName: "Paracetamol",
      activeIngredients: [{ name: "Paracetamol", strength: "500mg" }],
      therapeuticCategory: "Antipyretic",
      dosageForm: "Tablet",
      description: "Widely used paracetamol brand for pain and fever.",
      sideEffects: ["Nausea", "Rash"],
      packSize: "10 tablets",
      manufacturer: "Sanofi",
      brand: "Doliprane",
      isBranded: true,
      averagePrice: 25,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Paracip 650",
      genericName: "Paracetamol",
      activeIngredients: [{ name: "Paracetamol", strength: "650mg" }],
      therapeuticCategory: "Antipyretic",
      dosageForm: "Tablet",
      description: "Cipla's paracetamol for effective fever and pain relief.",
      sideEffects: ["Nausea", "Liver damage (overdose)"],
      warnings: ["Do not exceed 4g per day", "Avoid alcohol"],
      packSize: "15 tablets",
      manufacturer: "Cipla Ltd",
      brand: "Paracip",
      isBranded: true,
      averagePrice: 14,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },

    // ═══════════════════════════════════════════════
    //  AZITHROMYCIN ALTERNATIVES
    // ═══════════════════════════════════════════════
    {
      name: "Zithromax 500",
      genericName: "Azithromycin",
      activeIngredients: [{ name: "Azithromycin", strength: "500mg" }],
      therapeuticCategory: "Antibiotic",
      dosageForm: "Tablet",
      description: "Original Pfizer azithromycin for bacterial infections.",
      sideEffects: ["Diarrhea", "Nausea", "Abdominal pain"],
      warnings: ["Complete the full course"],
      packSize: "3 tablets",
      manufacturer: "Pfizer",
      brand: "Zithromax",
      isBranded: true,
      averagePrice: 120,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Azicip 500",
      genericName: "Azithromycin",
      activeIngredients: [{ name: "Azithromycin", strength: "500mg" }],
      therapeuticCategory: "Antibiotic",
      dosageForm: "Tablet",
      description: "Cipla azithromycin for respiratory and skin infections.",
      sideEffects: ["Diarrhea", "Nausea", "Vomiting"],
      packSize: "3 tablets",
      manufacturer: "Cipla Ltd",
      brand: "Azicip",
      isBranded: true,
      averagePrice: 72,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Azithral 500",
      genericName: "Azithromycin",
      activeIngredients: [{ name: "Azithromycin", strength: "500mg" }],
      therapeuticCategory: "Antibiotic",
      dosageForm: "Tablet",
      description: "Alembic azithromycin for bacterial infections.",
      sideEffects: ["Abdominal pain", "Diarrhea", "Nausea"],
      packSize: "3 tablets",
      manufacturer: "Alembic Pharma",
      brand: "Azithral",
      isBranded: true,
      averagePrice: 95,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Azilide 500",
      genericName: "Azithromycin",
      activeIngredients: [{ name: "Azithromycin", strength: "500mg" }],
      therapeuticCategory: "Antibiotic",
      dosageForm: "Tablet",
      description: "Azithromycin for ENT, respiratory and urogenital infections.",
      sideEffects: ["Diarrhea", "Stomach pain", "Headache"],
      packSize: "3 tablets",
      manufacturer: "Intas Pharmaceuticals",
      brand: "Azilide",
      isBranded: true,
      averagePrice: 68,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Azithromycin 500mg (Generic)",
      genericName: "Azithromycin",
      activeIngredients: [{ name: "Azithromycin", strength: "500mg" }],
      therapeuticCategory: "Antibiotic",
      dosageForm: "Tablet",
      description: "Unbranded generic azithromycin antibiotic.",
      sideEffects: ["Diarrhea", "Nausea"],
      packSize: "3 tablets",
      manufacturer: "Jan Aushadhi",
      brand: "Generic",
      isBranded: false,
      averagePrice: 35,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },

    // ═══════════════════════════════════════════════
    //  CETIRIZINE ALTERNATIVES
    // ═══════════════════════════════════════════════
    {
      name: "Zyrtec 10mg",
      genericName: "Cetirizine",
      activeIngredients: [{ name: "Cetirizine Hydrochloride", strength: "10mg" }],
      therapeuticCategory: "Antihistamine",
      dosageForm: "Tablet",
      description: "Antihistamine for allergy relief from UCB Pharma.",
      sideEffects: ["Drowsiness", "Dry mouth", "Fatigue"],
      packSize: "10 tablets",
      manufacturer: "UCB Pharma / Johnson & Johnson",
      brand: "Zyrtec",
      isBranded: true,
      averagePrice: 45,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Alerid 10mg",
      genericName: "Cetirizine",
      activeIngredients: [{ name: "Cetirizine Hydrochloride", strength: "10mg" }],
      therapeuticCategory: "Antihistamine",
      dosageForm: "Tablet",
      description: "Cipla's cetirizine for allergies, hay fever, and urticaria.",
      sideEffects: ["Drowsiness", "Headache"],
      packSize: "10 tablets",
      manufacturer: "Cipla Ltd",
      brand: "Alerid",
      isBranded: true,
      averagePrice: 28,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Okacet 10mg",
      genericName: "Cetirizine",
      activeIngredients: [{ name: "Cetirizine Hydrochloride", strength: "10mg" }],
      therapeuticCategory: "Antihistamine",
      dosageForm: "Tablet",
      description: "Cetirizine tablet for allergy symptoms relief.",
      sideEffects: ["Drowsiness", "Dry mouth"],
      packSize: "10 tablets",
      manufacturer: "Lupin Ltd",
      brand: "Okacet",
      isBranded: true,
      averagePrice: 30,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Cetirizine 10mg (Generic)",
      genericName: "Cetirizine",
      activeIngredients: [{ name: "Cetirizine Hydrochloride", strength: "10mg" }],
      therapeuticCategory: "Antihistamine",
      dosageForm: "Tablet",
      description: "Generic cetirizine for affordable allergy relief.",
      sideEffects: ["Drowsiness"],
      packSize: "10 tablets",
      manufacturer: "Jan Aushadhi",
      brand: "Generic",
      isBranded: false,
      averagePrice: 8,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },

    // ═══════════════════════════════════════════════
    //  METFORMIN ALTERNATIVES
    // ═══════════════════════════════════════════════
    {
      name: "Glucophage 500",
      genericName: "Metformin",
      activeIngredients: [{ name: "Metformin Hydrochloride", strength: "500mg" }],
      therapeuticCategory: "Antidiabetic",
      dosageForm: "Tablet",
      description: "Original metformin brand by Merck for type 2 diabetes.",
      sideEffects: ["Nausea", "Diarrhea", "Metallic taste"],
      warnings: ["Monitor kidney function"],
      packSize: "20 tablets",
      manufacturer: "Merck",
      brand: "Glucophage",
      isBranded: true,
      averagePrice: 45,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Cetapin 500",
      genericName: "Metformin",
      activeIngredients: [{ name: "Metformin Hydrochloride", strength: "500mg" }],
      therapeuticCategory: "Antidiabetic",
      dosageForm: "Tablet",
      description: "Cipla's metformin for blood sugar control in type 2 diabetes.",
      sideEffects: ["Nausea", "Abdominal discomfort", "Diarrhea"],
      packSize: "20 tablets",
      manufacturer: "Cipla Ltd",
      brand: "Cetapin",
      isBranded: true,
      averagePrice: 18,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Obimet 500",
      genericName: "Metformin",
      activeIngredients: [{ name: "Metformin Hydrochloride", strength: "500mg" }],
      therapeuticCategory: "Antidiabetic",
      dosageForm: "Tablet",
      description: "Metformin for managing type 2 diabetes mellitus.",
      sideEffects: ["Diarrhea", "Nausea", "Flatulence"],
      packSize: "20 tablets",
      manufacturer: "Abbott India",
      brand: "Obimet",
      isBranded: true,
      averagePrice: 25,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Metformin 500mg (Generic)",
      genericName: "Metformin",
      activeIngredients: [{ name: "Metformin Hydrochloride", strength: "500mg" }],
      therapeuticCategory: "Antidiabetic",
      dosageForm: "Tablet",
      description: "Generic metformin for affordable diabetes management.",
      sideEffects: ["Nausea", "Diarrhea"],
      packSize: "20 tablets",
      manufacturer: "Jan Aushadhi",
      brand: "Generic",
      isBranded: false,
      averagePrice: 7,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },

    // ═══════════════════════════════════════════════
    //  AMLODIPINE ALTERNATIVES
    // ═══════════════════════════════════════════════
    {
      name: "Norvasc 5mg",
      genericName: "Amlodipine",
      activeIngredients: [{ name: "Amlodipine Besylate", strength: "5mg" }],
      therapeuticCategory: "Antihypertensive",
      dosageForm: "Tablet",
      description: "Original Pfizer amlodipine for hypertension and angina.",
      sideEffects: ["Ankle swelling", "Dizziness", "Flushing"],
      warnings: ["Do not stop abruptly"],
      packSize: "10 tablets",
      manufacturer: "Pfizer",
      brand: "Norvasc",
      isBranded: true,
      averagePrice: 65,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Amlokind 5mg",
      genericName: "Amlodipine",
      activeIngredients: [{ name: "Amlodipine Besylate", strength: "5mg" }],
      therapeuticCategory: "Antihypertensive",
      dosageForm: "Tablet",
      description: "Mankind Pharma's amlodipine for blood pressure management.",
      sideEffects: ["Swelling", "Headache", "Fatigue"],
      packSize: "10 tablets",
      manufacturer: "Mankind Pharma",
      brand: "Amlokind",
      isBranded: true,
      averagePrice: 30,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Stamlo 5mg",
      genericName: "Amlodipine",
      activeIngredients: [{ name: "Amlodipine Besylate", strength: "5mg" }],
      therapeuticCategory: "Antihypertensive",
      dosageForm: "Tablet",
      description: "Dr. Reddy's amlodipine for hypertension.",
      sideEffects: ["Ankle edema", "Dizziness", "Palpitations"],
      packSize: "10 tablets",
      manufacturer: "Dr. Reddy's Labs",
      brand: "Stamlo",
      isBranded: true,
      averagePrice: 35,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Amlodipine 5mg (Generic)",
      genericName: "Amlodipine",
      activeIngredients: [{ name: "Amlodipine Besylate", strength: "5mg" }],
      therapeuticCategory: "Antihypertensive",
      dosageForm: "Tablet",
      description: "Generic amlodipine for affordable BP management.",
      sideEffects: ["Swelling", "Dizziness"],
      packSize: "10 tablets",
      manufacturer: "Jan Aushadhi",
      brand: "Generic",
      isBranded: false,
      averagePrice: 10,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },

    // ═══════════════════════════════════════════════
    //  OMEPRAZOLE ALTERNATIVES
    // ═══════════════════════════════════════════════
    {
      name: "Prilosec 20mg",
      genericName: "Omeprazole",
      activeIngredients: [{ name: "Omeprazole", strength: "20mg" }],
      therapeuticCategory: "Gastrointestinal",
      dosageForm: "Capsule",
      description: "AstraZeneca's omeprazole for acid reflux and GERD.",
      sideEffects: ["Headache", "Nausea", "Diarrhea"],
      packSize: "10 capsules",
      manufacturer: "AstraZeneca",
      brand: "Prilosec",
      isBranded: true,
      averagePrice: 80,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Ocid 20mg",
      genericName: "Omeprazole",
      activeIngredients: [{ name: "Omeprazole", strength: "20mg" }],
      therapeuticCategory: "Gastrointestinal",
      dosageForm: "Capsule",
      description: "Zydus omeprazole for gastric acid suppression.",
      sideEffects: ["Flatulence", "Headache"],
      packSize: "10 capsules",
      manufacturer: "Zydus Cadila",
      brand: "Ocid",
      isBranded: true,
      averagePrice: 42,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Omeprazole 20mg (Generic)",
      genericName: "Omeprazole",
      activeIngredients: [{ name: "Omeprazole", strength: "20mg" }],
      therapeuticCategory: "Gastrointestinal",
      dosageForm: "Capsule",
      description: "Generic omeprazole for acid reflux.",
      sideEffects: ["Headache", "Nausea"],
      packSize: "10 capsules",
      manufacturer: "Jan Aushadhi",
      brand: "Generic",
      isBranded: false,
      averagePrice: 12,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },

    // ═══════════════════════════════════════════════
    //  IBUPROFEN ALTERNATIVES
    // ═══════════════════════════════════════════════
    {
      name: "Advil 400mg",
      genericName: "Ibuprofen",
      activeIngredients: [{ name: "Ibuprofen", strength: "400mg" }],
      therapeuticCategory: "Analgesic",
      dosageForm: "Tablet",
      description: "Globally trusted ibuprofen brand for pain and inflammation.",
      sideEffects: ["Stomach upset", "Heartburn", "Dizziness"],
      warnings: ["Not for stomach ulcers"],
      packSize: "10 tablets",
      manufacturer: "Pfizer (Wyeth)",
      brand: "Advil",
      isBranded: true,
      averagePrice: 35,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Ibugesic 400mg",
      genericName: "Ibuprofen",
      activeIngredients: [{ name: "Ibuprofen", strength: "400mg" }],
      therapeuticCategory: "Analgesic",
      dosageForm: "Tablet",
      description: "Cipla ibuprofen for inflammatory conditions and pain.",
      sideEffects: ["Nausea", "Headache", "Stomach pain"],
      packSize: "10 tablets",
      manufacturer: "Cipla Ltd",
      brand: "Ibugesic",
      isBranded: true,
      averagePrice: 18,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Combiflam",
      genericName: "Ibuprofen",
      activeIngredients: [
        { name: "Ibuprofen", strength: "400mg" },
        { name: "Paracetamol", strength: "325mg" },
      ],
      therapeuticCategory: "Analgesic",
      dosageForm: "Tablet",
      description: "Dual-action pain reliever combining ibuprofen and paracetamol.",
      sideEffects: ["Nausea", "Stomach upset", "Drowsiness"],
      warnings: ["Not for prolonged use without medical advice"],
      packSize: "10 tablets",
      manufacturer: "Sanofi",
      brand: "Combiflam",
      isBranded: true,
      averagePrice: 32,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Ibuprofen 400mg (Generic)",
      genericName: "Ibuprofen",
      activeIngredients: [{ name: "Ibuprofen", strength: "400mg" }],
      therapeuticCategory: "Analgesic",
      dosageForm: "Tablet",
      description: "Generic ibuprofen for affordable pain management.",
      sideEffects: ["Stomach upset", "Heartburn"],
      packSize: "10 tablets",
      manufacturer: "Jan Aushadhi",
      brand: "Generic",
      isBranded: false,
      averagePrice: 6,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },

    // ═══════════════════════════════════════════════
    //  AMOXICILLIN ALTERNATIVES
    // ═══════════════════════════════════════════════
    {
      name: "Amoxil 500",
      genericName: "Amoxicillin",
      activeIngredients: [{ name: "Amoxicillin", strength: "500mg" }],
      therapeuticCategory: "Antibiotic",
      dosageForm: "Capsule",
      description: "GSK's amoxicillin for bacterial infections.",
      sideEffects: ["Diarrhea", "Allergic reactions", "Nausea"],
      warnings: ["Not for penicillin-allergic patients"],
      packSize: "10 capsules",
      manufacturer: "GlaxoSmithKline",
      brand: "Amoxil",
      isBranded: true,
      averagePrice: 75,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Novamox 500",
      genericName: "Amoxicillin",
      activeIngredients: [{ name: "Amoxicillin", strength: "500mg" }],
      therapeuticCategory: "Antibiotic",
      dosageForm: "Capsule",
      description: "Cipla amoxicillin for ear, respiratory and urinary infections.",
      sideEffects: ["Rash", "Diarrhea", "Vomiting"],
      packSize: "10 capsules",
      manufacturer: "Cipla Ltd",
      brand: "Novamox",
      isBranded: true,
      averagePrice: 50,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Wymox 500",
      genericName: "Amoxicillin",
      activeIngredients: [{ name: "Amoxicillin", strength: "500mg" }],
      therapeuticCategory: "Antibiotic",
      dosageForm: "Capsule",
      description: "Pfizer amoxicillin for broad spectrum infection coverage.",
      sideEffects: ["Diarrhea", "Nausea", "Skin rash"],
      packSize: "10 capsules",
      manufacturer: "Pfizer",
      brand: "Wymox",
      isBranded: true,
      averagePrice: 68,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Amoxicillin 500mg (Generic)",
      genericName: "Amoxicillin",
      activeIngredients: [{ name: "Amoxicillin", strength: "500mg" }],
      therapeuticCategory: "Antibiotic",
      dosageForm: "Capsule",
      description: "Generic amoxicillin for affordable antibiotic treatment.",
      sideEffects: ["Diarrhea", "Nausea"],
      packSize: "10 capsules",
      manufacturer: "Jan Aushadhi",
      brand: "Generic",
      isBranded: false,
      averagePrice: 20,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },

    // ═══════════════════════════════════════════════
    //  PANTOPRAZOLE ALTERNATIVES
    // ═══════════════════════════════════════════════
    {
      name: "Pantop 40mg",
      genericName: "Pantoprazole",
      activeIngredients: [{ name: "Pantoprazole Sodium", strength: "40mg" }],
      therapeuticCategory: "Gastrointestinal",
      dosageForm: "Tablet",
      description: "Aristo pantoprazole for acid reflux and peptic ulcer.",
      sideEffects: ["Headache", "Diarrhea"],
      packSize: "10 tablets",
      manufacturer: "Aristo Pharmaceuticals",
      brand: "Pantop",
      isBranded: true,
      averagePrice: 55,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Nupenta 40mg",
      genericName: "Pantoprazole",
      activeIngredients: [{ name: "Pantoprazole Sodium", strength: "40mg" }],
      therapeuticCategory: "Gastrointestinal",
      dosageForm: "Tablet",
      description: "Lupin's pantoprazole for GERD and acid-related disorders.",
      sideEffects: ["Nausea", "Flatulence", "Headache"],
      packSize: "10 tablets",
      manufacturer: "Lupin Ltd",
      brand: "Nupenta",
      isBranded: true,
      averagePrice: 48,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Pantoprazole 40mg (Generic)",
      genericName: "Pantoprazole",
      activeIngredients: [{ name: "Pantoprazole Sodium", strength: "40mg" }],
      therapeuticCategory: "Gastrointestinal",
      dosageForm: "Tablet",
      description: "Generic pantoprazole for affordable acid suppression.",
      sideEffects: ["Headache"],
      packSize: "10 tablets",
      manufacturer: "Jan Aushadhi",
      brand: "Generic",
      isBranded: false,
      averagePrice: 15,
      prescriptionRequired: false,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },

    // ═══════════════════════════════════════════════
    //  MONTELUKAST ALTERNATIVES
    // ═══════════════════════════════════════════════
    {
      name: "Singulair 10mg",
      genericName: "Montelukast",
      activeIngredients: [{ name: "Montelukast Sodium", strength: "10mg" }],
      therapeuticCategory: "Respiratory",
      dosageForm: "Tablet",
      description: "MSD's montelukast for asthma and allergic rhinitis.",
      sideEffects: ["Headache", "Abdominal pain"],
      warnings: ["Monitor for mood/behavioral changes"],
      packSize: "10 tablets",
      manufacturer: "MSD (Merck Sharp & Dohme)",
      brand: "Singulair",
      isBranded: true,
      averagePrice: 200,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Montek 10mg",
      genericName: "Montelukast",
      activeIngredients: [{ name: "Montelukast Sodium", strength: "10mg" }],
      therapeuticCategory: "Respiratory",
      dosageForm: "Tablet",
      description: "Sun Pharma montelukast for asthma prevention.",
      sideEffects: ["Headache", "Dizziness"],
      packSize: "10 tablets",
      manufacturer: "Sun Pharma",
      brand: "Montek",
      isBranded: true,
      averagePrice: 120,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Romilast 10mg",
      genericName: "Montelukast",
      activeIngredients: [{ name: "Montelukast Sodium", strength: "10mg" }],
      therapeuticCategory: "Respiratory",
      dosageForm: "Tablet",
      description: "Ranbaxy montelukast for asthma and allergies.",
      sideEffects: ["Headache", "Abdominal pain", "Fatigue"],
      packSize: "10 tablets",
      manufacturer: "Ranbaxy (Sun Pharma)",
      brand: "Romilast",
      isBranded: true,
      averagePrice: 105,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
    {
      name: "Montelukast 10mg (Generic)",
      genericName: "Montelukast",
      activeIngredients: [{ name: "Montelukast Sodium", strength: "10mg" }],
      therapeuticCategory: "Respiratory",
      dosageForm: "Tablet",
      description: "Generic montelukast for affordable asthma management.",
      sideEffects: ["Headache"],
      packSize: "10 tablets",
      manufacturer: "Jan Aushadhi",
      brand: "Generic",
      isBranded: false,
      averagePrice: 40,
      prescriptionRequired: true,
      regulatoryApproval: { approvedBy: "CDSCO", isApproved: true },
    },
  ];

  let created = 0;
  let skipped = 0;

  for (const med of alternatives) {
    const existing = await Medicine.findOne({ name: med.name });
    if (!existing) {
      await Medicine.create(med);
      console.log(`  💊 Created: ${med.name}`);
      created++;
    } else {
      console.log(`  ℹ️  Already exists: ${med.name}`);
      skipped++;
    }
  }

  // ── Auto-link equivalents by genericName ──
  console.log("\n🔗 Auto-linking equivalent medicines...");
  const genericNames = [...new Set(alternatives.map((m) => m.genericName))];

  for (const gName of genericNames) {
    const meds = await Medicine.find({ genericName: gName, isActive: true });
    if (meds.length > 1) {
      for (const med of meds) {
        med.equivalentMedicines = meds
          .filter((m) => m._id.toString() !== med._id.toString())
          .map((m) => m._id);
        await med.save();
      }
      console.log(`  🔗 Linked ${meds.length} "${gName}" equivalents`);
    }
  }

  console.log(`\n✅ Alternatives seed complete! Created: ${created}, Skipped: ${skipped}`);
  process.exit(0);
};

seedAlternatives().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
